### ISSUE TITLE
Example of how to change queue for worker

### ISSUE THREAD

**Issue by brandonjmckay** [lardawge/carrierwave_backgrounder#208]
@lardawge You recommended to override a worker as in: https://github.com/lardawge/carrierwave_backgrounder#override-worker

But I'm unclear as to how to override the sidekiq queue.

I've tried:

```
class MyImageProcessor < CarrierWave::Workers::ProcessAsset
  def queue
    :the_queue_i_want
  end
end
```

and

```
class MyImageProcessor < CarrierWave::Workers::ProcessAsset
  sidekiq_options({
    queue: :the_queue_i_want
  })
end
```

Neither work, so I'm assuming I'm using the wrong syntax. Can you provide an example of the correct syntax for that?

**Comment by lardawge** [comment]
Again, if all you're doing is overriding the queue name, this can be done in the config.

Are you passing your new worker as an argument to `#process_in_background`... other than that there is no magic.

**Comment by diazruy** [comment]
@lardawge the requirement is to change the queue for a particular set of uploaders, and not to **every** background uploader, which is what the config would accomplish. As a matter of fact, we do have a custom queue in the `config`, and this is "overriding" whatever we put in the Worker itself. 

```ruby
# config/initializers/carrierwave_backgrounder
CarrierWave::Backgrounder.configure do |c|
  c.backend :sidekiq, queue: :media_processing
end
```

The uploader is mounted with:

```ruby
mount_uploader :image, MyUploader
process_in_background :image, MyCustomWorker
```

with the worker being:
```ruby
class MyCustomWorker < CarrierWave::Workers::ProcessAsset
  include Sidekiq::Worker
  sidekiq_options({
    queue: :high_priority_media_processing
  })
end
```

But when uploading an image, it actually gets added to the `media_processing` queue instead of the `high_priority_media_processing` queue.

FWIW We're using carrierwave_backgrounder 0.4.1, carrierwave 0.10.0 and sidekiq 3.3.2.

**Comment by diazruy** [comment]
@lardawge when I commented out the custom queue in the `config` (`media_processing`), _then_ the queue set up in `sidekiq_options` for `MyCustomWorker` (`high_priority_media_processing`) **does** enqueue the job properly. However, now I'd have to add another custom worker to change the default queue for all other uploaders. Is it not possible to have both a default set through the config and override it on a case by case basis on individual workers?

**Comment by lardawge** [comment]
We may need to set this up when we are setting up the backend so that things don't get overridden.

Let me see what I can do.

**Comment by lardawge** [comment]
Try this branch and let me know if it works: https://github.com/lardawge/carrierwave_backgrounder/tree/do_not_override_queue_name

**Comment by diazruy** [comment]
@lardawge first off, thanks for taking the time to look into this. It is *very* much appreciated.

With the patch, the value passed in `sidekiq_options` now works correctly. However, the default from config no longer seems to work for other uploaders, as they are getting enqueued in the `default` queue instead of my custom `media_processing` one. 

I'm assuming it's because the `queue_options` from which you've deleted the `:queue` key must be a shared object between workers. Is it possible to inject the queue name somehow as part of the `sidekiq_queue_options`? Just spit-balling here... I don't understand the whole scope of the code, so it might not be as trivial as it might seem to the untrained eye.

**Comment by lardawge** [comment]
Tweaked the fix a little bit... need to add specs.. Will try to make time in the next few days. In the meantime, can you confirm it is working? Same branch.

**Comment by diazruy** [comment]
Needs a small tweak:

```diff
-            args['queue'] = queue_options[:queue] if queue_options[:queue] && worker.sidekiq_options['queue'] == 'default'
+            args['queue'] = queue_options[:queue] if queue_options[:queue] && args['class'].sidekiq_options['queue'] == 'default'
```

since `worker` is not defined in the `sidekiq_queue_options` method. Other than that, it seems to work!

**Comment by diazruy** [comment]
https://github.com/lardawge/carrierwave_backgrounder/pull/209

**Comment by lardawge** [comment]
I squished it down into on commit... same branch.

**Comment by lardawge** [comment]
Good catch

**Comment by diazruy** [comment]
Perfect! Works like a charm, thanks! :+1:

**Comment by lardawge** [comment]
I will get it spec'd and merge into master for a release.

**Comment by diazruy** [comment]
Great to hear. I've pointed my Gemfile to the branch but will update to the next gem release when available.

**Comment by thukim** [comment]
@lardawge : please check if this pull request solves the problem. (all specs passed)
https://github.com/lardawge/carrierwave_backgrounder/pull/212

**Comment by lardawge** [comment]
This is now in master... closing
